/* Auto-generated from Styles de texte.json */

export type TextStyleTemplate = {
  name: string;
  familyKind: "display" | "body";
  sizeToken: string;
  baseSize: number;
  lineHeightRatio: number;
  paragraphSpacingRatio: number;
  paragraphIndent: number;
  letterSpacingUnit: "PERCENT" | "PIXELS";
  letterSpacingValue: number;
  textCase: string;
  textDecoration: string;
  preferredFontStyle: string;
  fallbackWeight: number;
  italic: boolean;
};

export const TEXT_STYLE_TEMPLATES: TextStyleTemplate[] = [
  {
    "name": "Display 2xl/Bold",
    "familyKind": "display",
    "sizeToken": "display-2xl",
    "baseSize": 72,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Display 2xl/Medium",
    "familyKind": "display",
    "sizeToken": "display-2xl",
    "baseSize": 72,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Display 2xl/Regular",
    "familyKind": "display",
    "sizeToken": "display-2xl",
    "baseSize": 72,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Display 2xl/Semibold",
    "familyKind": "display",
    "sizeToken": "display-2xl",
    "baseSize": 72,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "SemiBold",
    "fallbackWeight": 600,
    "italic": false
  },
  {
    "name": "Display lg/Bold",
    "familyKind": "display",
    "sizeToken": "display-lg",
    "baseSize": 48,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Display lg/Medium",
    "familyKind": "display",
    "sizeToken": "display-lg",
    "baseSize": 48,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Display lg/Regular",
    "familyKind": "display",
    "sizeToken": "display-lg",
    "baseSize": 48,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Display lg/Semibold",
    "familyKind": "display",
    "sizeToken": "display-lg",
    "baseSize": 48,
    "lineHeightRatio": 1.25,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "SemiBold",
    "fallbackWeight": 600,
    "italic": false
  },
  {
    "name": "Display md/Bold",
    "familyKind": "display",
    "sizeToken": "display-md",
    "baseSize": 36,
    "lineHeightRatio": 1.2222,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Display md/Medium",
    "familyKind": "display",
    "sizeToken": "display-md",
    "baseSize": 36,
    "lineHeightRatio": 1.2222,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Display md/Regular",
    "familyKind": "display",
    "sizeToken": "display-md",
    "baseSize": 36,
    "lineHeightRatio": 1.2222,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Display md/Semibold",
    "familyKind": "display",
    "sizeToken": "display-md",
    "baseSize": 36,
    "lineHeightRatio": 1.2222,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "SemiBold",
    "fallbackWeight": 600,
    "italic": false
  },
  {
    "name": "Display sm/Bold",
    "familyKind": "display",
    "sizeToken": "display-sm",
    "baseSize": 30,
    "lineHeightRatio": 1.2667,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Display sm/Medium",
    "familyKind": "display",
    "sizeToken": "display-sm",
    "baseSize": 30,
    "lineHeightRatio": 1.2667,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Display sm/Medium italic",
    "familyKind": "display",
    "sizeToken": "display-sm",
    "baseSize": 30,
    "lineHeightRatio": 1.2667,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium Italic",
    "fallbackWeight": 500,
    "italic": true
  },
  {
    "name": "Display sm/Regular",
    "familyKind": "display",
    "sizeToken": "display-sm",
    "baseSize": 30,
    "lineHeightRatio": 1.2667,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Display sm/Semibold",
    "familyKind": "display",
    "sizeToken": "display-sm",
    "baseSize": 30,
    "lineHeightRatio": 1.2667,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "SemiBold",
    "fallbackWeight": 600,
    "italic": false
  },
  {
    "name": "Display xl/Bold",
    "familyKind": "display",
    "sizeToken": "display-xl",
    "baseSize": 60,
    "lineHeightRatio": 1.2,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Display xl/Medium",
    "familyKind": "display",
    "sizeToken": "display-xl",
    "baseSize": 60,
    "lineHeightRatio": 1.2,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Display xl/Regular",
    "familyKind": "display",
    "sizeToken": "display-xl",
    "baseSize": 60,
    "lineHeightRatio": 1.2,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Display xl/Semibold",
    "familyKind": "display",
    "sizeToken": "display-xl",
    "baseSize": 60,
    "lineHeightRatio": 1.2,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": -2,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "SemiBold",
    "fallbackWeight": 600,
    "italic": false
  },
  {
    "name": "Display xs/Bold",
    "familyKind": "display",
    "sizeToken": "display-xs",
    "baseSize": 24,
    "lineHeightRatio": 1.3333,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Display xs/Medium",
    "familyKind": "display",
    "sizeToken": "display-xs",
    "baseSize": 24,
    "lineHeightRatio": 1.3333,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Display xs/Medium italic",
    "familyKind": "display",
    "sizeToken": "display-xs",
    "baseSize": 24,
    "lineHeightRatio": 1.3333,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium Italic",
    "fallbackWeight": 500,
    "italic": true
  },
  {
    "name": "Display xs/Regular",
    "familyKind": "display",
    "sizeToken": "display-xs",
    "baseSize": 24,
    "lineHeightRatio": 1.3333,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Display xs/Semibold",
    "familyKind": "display",
    "sizeToken": "display-xs",
    "baseSize": 24,
    "lineHeightRatio": 1.3333,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "SemiBold",
    "fallbackWeight": 600,
    "italic": false
  },
  {
    "name": "Text lg/Bold",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text lg/Bold italic",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold Italic",
    "fallbackWeight": 700,
    "italic": true
  },
  {
    "name": "Text lg/Medium",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text lg/Medium italic",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium Italic",
    "fallbackWeight": 500,
    "italic": true
  },
  {
    "name": "Text lg/Medium underlined",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text lg/Regular",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text lg/Regular italic",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Italic",
    "fallbackWeight": 400,
    "italic": true
  },
  {
    "name": "Text lg/Regular underlined",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text lg/Semibold",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text lg/Semibold italic",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold Italic",
    "fallbackWeight": 700,
    "italic": true
  },
  {
    "name": "Text lg/Semibold underlined",
    "familyKind": "body",
    "sizeToken": "text-lg",
    "baseSize": 18,
    "lineHeightRatio": 1.5556,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text md/Bold",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text md/Bold italic",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold Italic",
    "fallbackWeight": 700,
    "italic": true
  },
  {
    "name": "Text md/Medium",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text md/Medium italic",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium Italic",
    "fallbackWeight": 500,
    "italic": true
  },
  {
    "name": "Text md/Medium underlined",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text md/Regular",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text md/Regular italic",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Italic",
    "fallbackWeight": 400,
    "italic": true
  },
  {
    "name": "Text md/Regular underlined",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text md/Semibold",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text md/Semibold italic",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold Italic",
    "fallbackWeight": 700,
    "italic": true
  },
  {
    "name": "Text md/Semibold underlined",
    "familyKind": "body",
    "sizeToken": "text-md",
    "baseSize": 16,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text sm/Bold",
    "familyKind": "body",
    "sizeToken": "text-sm",
    "baseSize": 14,
    "lineHeightRatio": 1.4286,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text sm/Medium",
    "familyKind": "body",
    "sizeToken": "text-sm",
    "baseSize": 14,
    "lineHeightRatio": 1.4286,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text sm/Medium underlined",
    "familyKind": "body",
    "sizeToken": "text-sm",
    "baseSize": 14,
    "lineHeightRatio": 1.4286,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text sm/Regular",
    "familyKind": "body",
    "sizeToken": "text-sm",
    "baseSize": 14,
    "lineHeightRatio": 1.4286,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text sm/Regular underlined",
    "familyKind": "body",
    "sizeToken": "text-sm",
    "baseSize": 14,
    "lineHeightRatio": 1.4286,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text sm/Semibold",
    "familyKind": "body",
    "sizeToken": "text-sm",
    "baseSize": 14,
    "lineHeightRatio": 1.4286,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text sm/Semibold underlined",
    "familyKind": "body",
    "sizeToken": "text-sm",
    "baseSize": 14,
    "lineHeightRatio": 1.4286,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text xl/Bold",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text xl/Bold italic",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold Italic",
    "fallbackWeight": 700,
    "italic": true
  },
  {
    "name": "Text xl/Medium",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text xl/Medium italic",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium Italic",
    "fallbackWeight": 500,
    "italic": true
  },
  {
    "name": "Text xl/Regular",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text xl/Regular italic",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Italic",
    "fallbackWeight": 400,
    "italic": true
  },
  {
    "name": "Text xl/Regular underlined",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "UNDERLINE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text xl/Semibold",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text xl/Semibold italic",
    "familyKind": "body",
    "sizeToken": "text-xl",
    "baseSize": 20,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold Italic",
    "fallbackWeight": 700,
    "italic": true
  },
  {
    "name": "Text xs/Bold",
    "familyKind": "body",
    "sizeToken": "text-xs",
    "baseSize": 12,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Bold",
    "fallbackWeight": 700,
    "italic": false
  },
  {
    "name": "Text xs/Medium",
    "familyKind": "body",
    "sizeToken": "text-xs",
    "baseSize": 12,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Medium",
    "fallbackWeight": 500,
    "italic": false
  },
  {
    "name": "Text xs/Regular",
    "familyKind": "body",
    "sizeToken": "text-xs",
    "baseSize": 12,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Regular",
    "fallbackWeight": 400,
    "italic": false
  },
  {
    "name": "Text xs/Semibold",
    "familyKind": "body",
    "sizeToken": "text-xs",
    "baseSize": 12,
    "lineHeightRatio": 1.5,
    "paragraphSpacingRatio": 1,
    "paragraphIndent": 0,
    "letterSpacingUnit": "PERCENT",
    "letterSpacingValue": 0,
    "textCase": "ORIGINAL",
    "textDecoration": "NONE",
    "preferredFontStyle": "Semi Bold",
    "fallbackWeight": 700,
    "italic": false
  }
];
